language: node_js

os: linux

node_js:
  - '10'
  - '12'

jobs:
  include:
    - stage: test
      script: npm t
    - stage: npm release
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_token: $NPM_TOKEN
        on:
          branch: master
          tags: true
